day=int(input("Введите количество дней: "))
hour=int(input("Введите количество часов: "))
minute=int(input("Введите количество минут: "))
second=int(input("Введите количество секунд: "))
print("Общее количество секунд: ", (second+minute*60+hour*3600+day*86400))